spring:
  application:
    name: project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Abcd123@

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: travel.project.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    travel.project.repository: trace
    travel.project.controller: debug

