#spring:
#  config:
#    activate:
#      on-profile:
#      - test
      
#
#  datasource:
#   url: jdbc:h2:mem:test
#   username: sa
#   password:

mybatis:
  type-aliases-package: travel.project.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true